### ISSUE TITLE
Range actions are not supported Exception

### ISSUE THREAD

**Issue by milos12345** [mattleibow/RangedObservableCollection#1]
I replaced my ObservableCollection with this one and I get 

> System.NotSupportedException: 'Range actions are not supported.'

 on line

`OnCollectionChanged(new NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction.Add, changedItems, startIndex));`

Using WPF and .NET 4.8. Am I missing something?

Edit: more info:

 Stack Trace

>   at System.Windows.Data.ListCollectionView.ValidateCollectionChangedEventArgs(NotifyCollectionChangedEventArgs e)
>    at System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
>    at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
>    at System.Collections.ObjectModel.RangedObservableCollection`1.AddRange(IEnumerable`1 collection) in D:\...\RangedObservableCollection.cs:line 

when I try

```
List<object> templist = new List<object>();
...
FilesCollection.AddRange(templist);
```

**Comment by PieterjanDeClippel** [comment]
I've been able to fix this like this: https://github.com/MintPlayer/MintPlayer.ObservableCollection/commit/3c4a0ea517c9f64c13b4432ee678a1386dc587f8

Basically, you cannot call `OnCollectionChanged` because that would trigger a Range operation.

What you can do instead is loop through all handlers. If the handler is bound from a CollectionView, you can just call the `Refresh()` method on the CollectionView. Otherwise you can just invoke the handler.
